
try {

} catch (error) {
    print("An error occurred: " + error.message);
}